#! /bin/bash

set -e
(
dpkg-divert --package se3 --add --rename --divert /etc/.cron_mrtg.divert /etc/cron.d/mrtg
dpkg-divert --package se3 --add --rename --divert /etc/mrtg.cfg.divert /etc/mrtg.cfg 

dpkg-divert --package se3 --add --rename --divert /etc/cups/mime.convs.divert  /etc/cups/mime.convs 
dpkg-divert --package se3 --add --rename --divert /etc/cups/mime.types.divert  /etc/cups/mime.types 
dpkg-divert --package se3 --add --rename --divert /etc/syslog.conf.divert /etc/syslog.conf 

dpkg-divert --package se3 --add --rename --divert /usr/share/se3/scripts/start_poste.divert /usr/share/se3/scripts/start_poste.sh

# No rename, may have real conf in place (reinstall for exemple)
dpkg-divert --package se3 --add --divert /etc/samba/smb.conf.divert  /etc/samba/smb.conf 
dpkg-divert --package se3 --add --divert  /etc/ssmtp/ssmtp.conf.divert  /etc/ssmtp/ssmtp.conf 
dpkg-divert --package se3 --add --divert /etc/backuppc/localhost.pl.divert  /etc/backuppc/localhost.pl
dpkg-divert --package se3 --add --divert  /etc/ldap/slapd.conf.divert /etc/ldap/slapd.conf
dpkg-divert --package se3 --add --divert  /etc/ldap/ldap.conf.divert /etc/ldap/ldap.conf 
dpkg-divert --package se3 --add --divert  /etc/nsswitch.conf.divert /etc/nsswitch.conf 
dpkg-divert --package se3 --add --divert  /etc/pam_ldap.conf.divert /etc/pam_ldap.conf 
dpkg-divert --package se3 --add --divert  /etc/libnss-ldap.conf.divert /etc/libnss-ldap.conf 
) >/dev/null

# Nettoyage sbin

if [ -e /usr/share/se3/sbin/permse3 ]; then
rm -f /usr/share/se3/sbin/permse3
ln -s /usr/share/se3/scripts/permse3 /usr/share/se3/sbin/permse3 
fi

if [ -e /usr/share/se3/sbin/restore_droits.sh ]; then
rm -f /usr/share/se3/sbin/restore_droits.sh
ln -s /usr/share/se3/scripts/restore_droits /usr/share/se3/sbin/restore_droits.sh 
fi




#if [ -e  ]; then
#rm -f 
#fi

# Nettoyage scripts


if [ -e /usr/share/se3/scripts/verif_client.sh ]; then
rm -f /usr/share/se3/scripts/verif_client.sh
fi

exit 0
