#!/bin/bash -e
# Automatically added by dh_installdocs
if [ "$1" = "remove" ]; then
	rm -f /usr/doc/se3
	rm -f /usr/share/doc/se3
	cd /var/cache/se3_install/
	./uninstall.sh
fi
# End automatically added section
