#!/bin/bash
#
##### Permet d'afficher la liste des scripts et l'aide correspondante #####
#
## $Id$ ##

if [ "$1" == "--help" -o "$1" == "-h" ]
then
	echo "Permet d'obtenir la fonction de chaque script de SambaEdu"
	echo "Les scripts se trouve dans /usr/share/se3/[sbin ou script]" 
	echo "Usage : aidese3 [début du nom] pour n'avoir que les scripts commençant par"
	echo "--help cette aide"
	
	exit
fi

#Couleurs
COLTITRE="\033[1;35m"   # Rose
COLPARTIE="\033[1;34m"  # Bleu

COLTXT="\033[0;37m"     # Gris
COLCHOIX="\033[1;33m"   # Jaune
COLDEFAUT="\033[0;33m"  # Brun-jaune
COLSAISIE="\033[1;32m"  # Vert

COLCMD="\033[1;37m"     # Blanc

COLERREUR="\033[1;31m"  # Rouge
COLINFO="\033[0;36m"    # Cyan



if [ "$1" != "" ]
then
	LIST="$1*"
fi	
cd /usr/share/se3/sbin
echo -e "$COLERREUR ======================== sbin ================================================"
ls $LIST 2> /dev/null | while read C 
do
#	perl  -ne 'print $1 if /^#{5}(.*)#{5}$/' $A
	AIDE=`grep "^##### .* #####$" $C | cut -d\# -f6`
	if [ "$C" != "aidese3" ]
	then
		VERS=`cat $C | grep '$Id:' | cut -d: -f2 | cut -d" " -f3`
	fi	
	if [ "$AIDE" != "" ]
	then
		echo -e "$COLTITRE $C $COLINFO $VERS $COLCMD $AIDE"
	fi	
AIDE=""
VERS=""
done

cd /usr/share/se3/scripts

echo -e "$COLERREUR ======================== scripts ================================================"
ls $LIST 2> /dev/null | while read D
do
	AIDE=`grep "^##### .* #####$" $D | cut -d\# -f6`
	VERS=`cat $D | grep '$Id:' | cut -d: -f2 | cut -d" " -f 3`
	if [ "$AIDE" != "" ]
	then

		echo -e "$COLTITRE $D $COLINFO $VERS $COLCMD $AIDE"
	fi	
AIDE=""
VERS=""
done
