Document: sambaedu-master
Title: Debian sambaedu-master Manual
Author: <insert document author here>
Abstract: This manual describes what sambaedu-master is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sambaedu-master/sambaedu-master.sgml.gz

Format: postscript
Files: /usr/share/doc/sambaedu-master/sambaedu-master.ps.gz

Format: text
Files: /usr/share/doc/sambaedu-master/sambaedu-master.text.gz

Format: HTML
Index: /usr/share/doc/sambaedu-master/html/index.html
Files: /usr/share/doc/sambaedu-master/html/*.html
